config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  default_scope { order("created_at DESC") }

  scope :with_job, -> { where('job_id is not null') }
  scope :pending, -> { with_state(:pending) }
  scope :transcoding, -> { with_job.with_state(:transcoding) }
  scope :transcoded, -> { with_job.with_state(:transcoded) }
  scope :failed, -> { with_job.with_state(:failed) }

  mount_uploader :original_file, VideoUploader

  validates_presence_of :original_file

  state_machine initial: :pending do
    event :scheduled do
      transition :pending => :transcoding
    end

    event :finished do
      transition :transcoding => :transcoded
    end

    event :failed do
      transition [:pending, :transcoding] => :failed
    end
  end

  def name
    original_file_identifier
  end

  def name_without_extension
    name.split('.')[0...-1].join
  end

  def readable_date
    created_at.strftime('%d-%b %H:%M')
  end

  def readable_size
    if size_in_bytes
      "#{size_in_bytes / 1024} Kbytes"
    else
      "Unavailable"
    end
  end

  def readable_duration
    if duration
      "#{duration / 1000} secs"
    else
      "Unavailable"
    end
  end

  def has_errors?
    errors.present?
  end
end

app/models/zencoder_job_builder.rb
# Utitlity class to create a hash representing a new
#  job request to send to Zencoder api
class ZencoderJobBuilder
  def initialize(video)
    @video = video
  end

  def build_payload
    {
      input: "s3://videoencodercodechallenge/#{Rails.env}/originals/#{@video.id}/#{@video.name}",
      outputs: [
        {
          label: "#{@video.name} (MP4)",
          url: "s3://videoencodercodechallenge/#{Rails.env}/transcoded/#{@video.id}/#{@video.name_without_extension}.mp4",
          h264_profile: 'high',
          public: true
        }
      ]
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Home controller displays only the welcome screen
  #  with information about the application
  def index; end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(parameters)
    video_scheduler = VideoSchedulerService.new(@video)

    if video_scheduler.create
      redirect_to videos_path, notice: 'Your video has been scheduled to encode'
    else
      render action: :new
    end
  end

  def show
    @video = Video.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404.html', status: :not_found
  end

  private

  def parameters
    params.fetch(:video, {}).permit(:original_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Helper classes to build the main menu marking the
  #  active menu item with different css class
  module UI
    # Represents a item in a menu. The tag attribute is used
    #  to decorate each item with a TAG css class
    class MenuItem
      attr_accessor :url, :tag, :active, :title

      def initialize(params)
        @url = params[:url]
        @tag = params[:tag]
        @active = params[:active]
        @title = params[:title]
      end

      def css_class
        classes = ['mdl-layout__tab']
        classes << 'is-active' if active
        classes.join(' ')
      end
    end

    # Used to build the application's menu on each page
    class Menu
      delegate :url_helpers, to: 'Rails.application.routes'

      def initialize(active_item = :home)
        @active_item = active_item
      end

      def items
        build_items.each do |item|
          item.active = active_item?(item.tag)
        end
      end

      private

      def active_item?(tag)
        @active_item == tag
      end

      def build_items
        [
          MenuItem.new(title: 'Overview', tag: :home,
                       url: url_helpers.root_path,
                       active: true),

          MenuItem.new(title: 'Videos', tag: :videos,
                       url: url_helpers.videos_path,
                       active: false)
        ]
      end
    end

    # Display flash messages
    class Flash
      attr_accessor :msg

      def initialize(msg = nil)
        @msg = msg
      end

      def show
        return if msg.nil?
        "<div class='alert-info'>#{msg}</div>".html_safe
      end
    end
  end
end

app/views/home/index.html.erb
<% content_for(:menu) do %>
  <%= render :partial => 'shared/menu', :locals => {current: :home} %>
<% end %>

<% content_for(:content) do %>
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
    <div class="mdl-card mdl-cell mdl-cell--12-col">
      <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
        <h4 class="mdl-cell mdl-cell--12-col">Stack</h4>
        <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
          <div class="section__circle-container__circle mdl-color--accent"><i class="material-icons icone-inserido">settings</i></div>
        </div>
        <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
          <h5>Backend</h5>
          Rails 5.1.4, Ruby 2.4.2 and SQLite 3
        </div>

        <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
          <div class="section__circle-container__circle mdl-color--accent"><i class="material-icons icone-inserido">code</i></div>
        </div>
        <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
          <h5>Frontend</h5>
          Material Design (HTML5/CSS), jQuery, Dropify and videojs.
        </div>

        <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
          <div class="section__circle-container__circle mdl-color--accent"><i class="material-icons icone-inserido">extension</i></div>
        </div>
        <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
          <h5>Midleware</h5>
          Sidekiq and Redis
        </div>

        <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
          <div class="section__circle-container__circle mdl-color--accent"><i class="material-icons icone-inserido">computer</i></div>
        </div>
        <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
          <h5>Integrations</h5>
          AWS S3, Zencoder API
        </div>

        <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
          <div class="section__circle-container__circle mdl-color--accent"><i class="material-icons icone-inserido">face</i></div>
        </div>
        <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
          <h5>Quality</h5>
          RSpec, Rubocop
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/layouts/application.html.erb
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Code Challenge</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.deep_purple-pink.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">

    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
          <h3>Code Challenge</h3>
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>

        <%= yield :menu %>

      </header>
      <main class="mdl-layout__content">
        <div class="mdl-layout__tab-panel is-active">
          <%= yield :content %>
        </div>
      </main>
    </div>
    <script src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/shared/_menu.html.erb
<div class="mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark">
  <% ApplicationHelper::UI::Menu.new(current).items.each do |item| %>
    <%= link_to item.title, item.url,
     class: item.css_class %>
  <% end %>
</div>

app/views/videos/_empty_list.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text">
      <h4 class="mdl-cell mdl-cell--12-col">No videos yet</h4>
      <p>
        You haven't submited any video to be encoded. Upload a
        <strong>mp4</strong>, <strong>ogg</strong> or <strong>webm</strong>
         to encoded to <strong>mp4</strong>
      </p>
      <p>
        <%= link_to 'Upload', new_video_path,
          class: 'mdl-button mdl-js-button mdl-button--raised
            mdl-js-ripple-effect mdl-button--accent' %>
      </p>
    </div>
  </div>
</section>

app/views/videos/_form.html.erb
<%= simple_form_for @video do |f| %>

  <% if @video.has_errors? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <%= @video.errors.full_messages.join('. ') %>
      </div>
    </div>
  <% end %>

  <%= f.input :original_file, label: false, error: false, input_html: {class: 'dropify', data: {height: "80"}} %>
  <%= f.submit 'Upload', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
<% end %>

app/views/videos/_list.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text">
      <h4 class="mdl-cell mdl-cell--12-col">
        Uploaded videos

        <%= link_to 'Upload', new_video_path,
          class: 'mdl-button mdl-js-button mdl-button--raised
            mdl-js-ripple-effect mdl-button--accent botao-atualizar-videos' %>

        <%= link_to 'Update status', videos_path,
          class: 'mdl-button mdl-js-button mdl-button--raised
            mdl-js-ripple-effect mdl-button--accent botao-atualizar-videos' %>
      </h4>

      <%= ApplicationHelper::UI::Flash.new(flash[:notice]).show %>
      
      <table class="mdl-data-table mdl-shadow--2dp mdl-cell--12-col">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Original file</th>
            <th>Job ID</th>
            <th>Date</th>
            <th class="mdl-data-table__cell--non-numeric">Status</th>
          </tr>
        </thead>
        <tbody>
          <%= render @videos %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/videos/_player_failed.html.erb
<div id="explanation">
  <div class="alert alert-info">
    The transcode has failed. Please choose another video and try again
  </div>
</div>

app/views/videos/_player_pending.html.erb
<div id="explanation">
  <div class="alert alert-info">
    Your video have not been sent to encode yet
  </div>
</div>

app/views/videos/_player_transcoded.html.erb
<video id="my-video" class="video-js" controls preload="auto" width="<%= @video.width %>" height="<%= @video.height %>" data-setup="{}">
  <source src="<%= @video.converted_file %>" type='video/mp4'>
  <p class="vjs-no-js">
    To watch this video, enable javascript in your web browser
    <a href="http://videojs.com/html5-video-support/" target="_blank">HTML5 Support</a>
  </p>
</video>

app/views/videos/_player_transcoding.html.erb
<div id="explanation">
  <div class="alert alert-info">
    The job is still pending on Zencoder. Wait few minutes and refresh this
    page to get an updated status
  </div>
</div>

app/views/videos/_video.html.erb
<tr>
  <td class="mdl-data-table__cell--non-numeric">
    <%= video.name %>
    <%= link_to ' (watch)', video_path(video) if video.transcoded? %>
  </td>
  <td><%= video.job_id %></td>
  <td><%= video.readable_date %></td>
  <td class="mdl-data-table__cell--non-numeric"><span class='info-label <%= video.state %>'><%= video.state %></span></td>
</tr>

app/views/videos/index.html.erb
<% content_for(:menu) do %>
  <%= render partial: 'shared/menu', locals: {current: :videos} %>
<% end %>

<% content_for(:content) do %>
  <% if @videos.any? %>
    <%= render partial: 'list' %>
  <% else %>
    <%= render partial: 'empty_list' %>
  <% end %>
<% end %>

app/views/videos/new.html.erb
<% content_for(:menu) do %>
  <%= render :partial => 'shared/menu', locals: {current: :videos} %>
<% end %>

<% content_for(:content) do %>
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
    <div class="mdl-card mdl-cell mdl-cell--12-col">
      <div class="mdl-card__supporting-text">
        <h4 class="mdl-cell mdl-cell--12-col">New video</h4>
        <%= render 'form' %>
      </div>
    </div>
  </section>
<% end %>

app/views/videos/show.html.erb
<% content_for(:menu) do %>
  <%= render partial: 'shared/menu', locals: {current: :videos} %>
<% end %>

<% content_for(:content) do %>
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
    <div class="mdl-card mdl-cell mdl-cell--12-col">
      <div class="mdl-card__supporting-text">
        <h4 class="mdl-cell mdl-cell--12-col">
          Watch the video
        </h4>

        <%= render :partial => "player_#{@video.state}" %>

        <table class="mdl-data-table mdl-shadow--2dp mdl-cell--12-col" style="width: 100%">
          <tbody>
            <tr>
              <th>Status</th>
              <td><span class='info-label <%= @video.state %>'><%= @video.state %></span></td>
            </tr>
            <tr>
              <th>Input</th>
              <td><%= @video.name %></td>
            </tr>
            <tr>
              <th>Output</th>
              <td><%= @video.converted_file %></td>
            </tr>
            <tr>
              <th>Tamanho</th>
              <td><%= @video.readable_size %></td>
            </tr>
            <tr>
              <th>Duration</th>
              <td><%= @video.readable_duration %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>
<% end %>